-- MySQL Script generated by MySQL Workbench
-- lun 26 sep 2016 23:27:05 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET latin1 ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`casa` (
  `ciudad` VARCHAR(40) NOT NULL,
  `calle` VARCHAR(40) NOT NULL,
  `poblacion` VARCHAR(40) NOT NULL,
  `idcasa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcasa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prueba`.`Tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Tiene` (
  `DNI` INT(11) NOT NULL,
  `idcasa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `idcasa`),
  INDEX `fk_Tiene_casa1_idx` (`idcasa` ASC),
  CONSTRAINT `fk_Tiene_casa1`
    FOREIGN KEY (`idcasa`)
    REFERENCES `prueba`.`casa` (`idcasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prueba`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Propietario` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `Edad` INT(11) NOT NULL,
  `DNI` INT(11) NOT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `fk_Propietario_Tiene`
    FOREIGN KEY (`DNI`)
    REFERENCES `prueba`.`Tiene` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
